### ISSUE TITLE
Integrate missing information for verification

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#44]
We need to integrate the following missing info about ceremony verification.

### Data
- [x] External link to circuit template source + commit hash
- [x] Circuit compiler: version + commit hash
- [x] Verification software (#52)
- [x] Public finalization beacon (#35) 
- [x] Number of iterations used for finalization (encoded in configs)
- [x] Contribution:
   - [x] Contribution signature by hashing the computed points (tau, alpha, beta) (already implemented on Groth16)
   - [x] Previous contribution signature (already implemented on Groth16)
   - [x] Contributor unique ID (#50)
- [ ] Store public attestation gist (#19)

### Artifacts
- [x] Link to contributions (zKey) + hash
- [x] Link to R1CS + hash
- [x] Link to Phase 1 artifacts (PoT) + hash + source
- [x] Link to transcript + hash
- [x] Ceremony Output
   - [x] Link to final contribution (zKey) + hash
   - [x] Link to verifier contract + hash 
   - [x] Link to verification keys + hash
